import { ExerciseRoutine } from "@/types";

export const EXERCISE_LIBRARY: ExerciseRoutine[] = [
  {
    id: "routine-full-body-core",
    title: "Full Body Strength & Core Awakening",
    category: "strength",
    difficulty: "beginner",
    estimatedMinutes: 30,
    caloriesBurnedEstimate: 210,
    exercises: [
      {
        name: "Bodyweight Air Squats",
        sets: 3,
        reps: "12-15 reps",
        restSeconds: 45,
        targetMuscles: "Quadriceps, Glutes, Hamstrings",
        coachingTips: "Keep chest tall, push hips back, drive through heels.",
        alternativeForInjury: "Box squats or seated leg extensions",
      },
      {
        name: "Incline or Knee Push-Ups",
        sets: 3,
        reps: "10-12 reps",
        restSeconds: 45,
        targetMuscles: "Chest, Shoulders, Triceps",
        coachingTips: "Maintain a rigid plank line from crown to heels.",
        alternativeForInjury: "Resistance band chest press",
      },
      {
        name: "Glute Bridges with 2-Sec Squeeze",
        sets: 3,
        reps: "15 reps",
        restSeconds: 30,
        targetMuscles: "Glutes, Lower Back, Hamstrings",
        coachingTips: "Drive through heels, squeeze glutes at peak for 2 seconds.",
        alternativeForInjury: "Standing kickbacks",
      },
      {
        name: "Dead Bug Core Stabilization",
        sets: 3,
        reps: "10 reps / side",
        restSeconds: 30,
        targetMuscles: "Transverse Abdominis, Core",
        coachingTips: "Press lower back firmly into the floor throughout.",
        alternativeForInjury: "Bird-dog on hands and knees",
      },
    ],
  },
  {
    id: "routine-hiit-burn",
    title: "Low-Impact Cardio & Fat Burner",
    category: "hiit",
    difficulty: "intermediate",
    estimatedMinutes: 25,
    caloriesBurnedEstimate: 240,
    exercises: [
      {
        name: "Brisk Step-Jacks (No Jump)",
        sets: 4,
        reps: "45 sec on / 15 sec off",
        restSeconds: 15,
        targetMuscles: "Full Body, Cardiovascular System",
        coachingTips: "Step side to side rapidly while extending arms overhead.",
        alternativeForInjury: "Seated arm pump cadence",
      },
      {
        name: "Alternating Reverse Lunges",
        sets: 3,
        reps: "10 reps / leg",
        restSeconds: 45,
        targetMuscles: "Quadriceps, Glutes",
        coachingTips: "Step backward softly; keep front knee aligned with second toe.",
        alternativeForInjury: "Step-ups onto a low sturdy step",
      },
      {
        name: "Mountain Climbers (Paced)",
        sets: 3,
        reps: "30 seconds",
        restSeconds: 30,
        targetMuscles: "Shoulders, Core, Hip Flexors",
        coachingTips: "Keep hips level with shoulders; drive knees rhythmically.",
        alternativeForInjury: "Standing high knee marches",
      },
    ],
  },
  {
    id: "routine-mobility-recovery",
    title: "Deep Posture Reset & Hip Mobility Flow",
    category: "mobility",
    difficulty: "beginner",
    estimatedMinutes: 20,
    caloriesBurnedEstimate: 95,
    exercises: [
      {
        name: "Cat-Cow Spinal Articulation",
        sets: 2,
        reps: "10 smooth breaths",
        restSeconds: 20,
        targetMuscles: "Entire Spine, Neck, Abdominals",
        coachingTips: "Inhale arching gently, exhale rounding spine smoothly.",
      },
      {
        name: "90/90 Hip Mobility Rotations",
        sets: 2,
        reps: "8 rotations / side",
        restSeconds: 30,
        targetMuscles: "Hip Internal & External Rotators",
        coachingTips: "Sit upright, transition hips side to side without rushing.",
      },
      {
        name: "Child's Pose to Upward Dog Transition",
        sets: 2,
        reps: "6 slow passes",
        restSeconds: 30,
        targetMuscles: "Lats, Chest, Lumbar Spine",
        coachingTips: "Breathe deeply into ribcage at end range.",
      },
    ],
  },
];
